import { getNormalizedKey } from "./im-dom";

/** Keyboard keys */
export const KEY = {
    // 1 to 9,0 - main numbers
    A1: getNormalizedKey("1"),
    A2: getNormalizedKey("2"),
    A3: getNormalizedKey("3"),
    A4: getNormalizedKey("4"),
    A5: getNormalizedKey("5"),
    A6: getNormalizedKey("6"),
    A7: getNormalizedKey("7"),
    A8: getNormalizedKey("8"),
    A9: getNormalizedKey("9"),
    A0: getNormalizedKey("0"),
    MINUS: getNormalizedKey("-"),
    EQUALS: getNormalizedKey("="),

    Q: getNormalizedKey("Q"),
    W: getNormalizedKey("W"),
    E: getNormalizedKey("E"),
    R: getNormalizedKey("R"),
    T: getNormalizedKey("T"),
    Y: getNormalizedKey("Y"),
    U: getNormalizedKey("U"),
    I: getNormalizedKey("I"),
    O: getNormalizedKey("O"),
    P: getNormalizedKey("P"),
    OPEN_BRACKET: getNormalizedKey("["),
    CLOSE_BRACKET: getNormalizedKey("]"),
    BACKSLASH: getNormalizedKey("\\"),

    A: getNormalizedKey("A"),
    S: getNormalizedKey("S"),
    D: getNormalizedKey("D"),
    F: getNormalizedKey("F"),
    G: getNormalizedKey("G"),
    H: getNormalizedKey("H"),
    J: getNormalizedKey("J"),
    K: getNormalizedKey("K"),
    L: getNormalizedKey("L"),
    SEMICOLON: getNormalizedKey(";"),
    QUOTE: getNormalizedKey("'"),
    ENTER: getNormalizedKey("Enter"),

    Z: getNormalizedKey("Z"),
    X: getNormalizedKey("X"),
    C: getNormalizedKey("C"),
    V: getNormalizedKey("V"),
    B: getNormalizedKey("B"),
    N: getNormalizedKey("N"),
    M: getNormalizedKey("M"),
    COMMA: getNormalizedKey(","),
    PERIOD: getNormalizedKey("."),
    FORWARD_SLASH: getNormalizedKey("/"),

    // Modifiers & Navigation
    SHIFT: getNormalizedKey("Shift"),
    CTRL: getNormalizedKey("Control"),
    META: getNormalizedKey("Meta"),
    ALT: getNormalizedKey("Alt"),
    TAB: getNormalizedKey("Tab"),
    MOD: getNormalizedKey("Modifier"), 

    SPACE: getNormalizedKey(" "),
    DELETE: getNormalizedKey("Delete"),
    INSERT: getNormalizedKey("Insert"),
    PAGE_UP: getNormalizedKey("PageUp"),
    PAGE_DOWN: getNormalizedKey("PageDown"), // Added
    HOME: getNormalizedKey("Home"), // Added
    END: getNormalizedKey("End"), // Added
    BACKSPACE: getNormalizedKey("Backspace"),
    ARROW_UP: getNormalizedKey("ArrowUp"),
    ARROW_DOWN: getNormalizedKey("ArrowDown"),
    ARROW_LEFT: getNormalizedKey("ArrowLeft"),
    ARROW_RIGHT: getNormalizedKey("ArrowRight"),

    // Function keys
    F1: getNormalizedKey("F1"),
    F2: getNormalizedKey("F2"),
    F3: getNormalizedKey("F3"),
    F4: getNormalizedKey("F4"),
    F5: getNormalizedKey("F5"),
    F6: getNormalizedKey("F6"),
    F7: getNormalizedKey("F7"),
    F8: getNormalizedKey("F8"),
    F9: getNormalizedKey("F9"),
    F10: getNormalizedKey("F10"),
    F11: getNormalizedKey("F11"),
    F12: getNormalizedKey("F12"),

    // System keys
    ESCAPE: getNormalizedKey("Escape"),
    CAPS_LOCK: getNormalizedKey("CapsLock"),
    SCROLL_LOCK: getNormalizedKey("ScrollLock"),
    NUM_LOCK: getNormalizedKey("NumLock"),
    PRINT_SCREEN: getNormalizedKey("PrintScreen"),
    PAUSE: getNormalizedKey("Pause"),
    CONTEXT_MENU: getNormalizedKey("ContextMenu"),

    // Numpad
    NUMPAD_0: getNormalizedKey("0"),
    NUMPAD_1: getNormalizedKey("1"),
    NUMPAD_2: getNormalizedKey("2"),
    NUMPAD_3: getNormalizedKey("3"),
    NUMPAD_4: getNormalizedKey("4"),
    NUMPAD_5: getNormalizedKey("5"),
    NUMPAD_6: getNormalizedKey("6"),
    NUMPAD_7: getNormalizedKey("7"),
    NUMPAD_8: getNormalizedKey("8"),
    NUMPAD_9: getNormalizedKey("9"),
    NUMPAD_DECIMAL: getNormalizedKey("."),
    NUMPAD_DIVIDE: getNormalizedKey("/"),
    NUMPAD_MULTIPLY: getNormalizedKey("*"),
    NUMPAD_SUBTRACT: getNormalizedKey("-"),
    NUMPAD_ADD: getNormalizedKey("+"),
    NUMPAD_ENTER: getNormalizedKey("Enter"),

    // Additional common punctuation symbols
    BACKTICK: getNormalizedKey("`"),
} as const;
